baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
paginate = 6

markup.tableOfContents = { endLevel = 6, ordered = false, startLevel = 2 }

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"

[taxonomies]
  category = 'categories'
  tag = 'tags'
  group = 'group'

[[menu.main]]
  name = "Projects"
  url = "/projects/"
  weight = 1

[[menu.main]]
  name = "Notes"
  url = "/notes/"
  weight = 2
